name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env.production
          echo Stream_CHAT_API_KEY=${{secrets.Stream_CHAT_API_KEY}} >> .env.production
          echo Stream_CHAT_SECRET=${{ secrets.Stream_CHAT_SECRET }} >> .env.production
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.production
          echo DATABASE_NAME=${{secrets.DATABASE_NAME}} >> .env.production
          JWT_SECRET=${{secrets.JWT_SECRET}} >> .env.production
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env.production
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env.production
          echo BUCKET_NAME=sq-chatapp-prod >> .env.production
          echo PORT=80 >> .env.production
          cat .env.production
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shuangqiu/chatapp:latest

