name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shuangqiu/chatapp:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            "Stream_CHAT_API_KEY=${{secrets.Stream_CHAT_API_KEY}}"
            "Stream_CHAT_SECRET=${{ secrets.Stream_CHAT_SECRET }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "DATABASE_NAME=${{secrets.DATABASE_NAME}}"
            "JWT_SECRET=${{secrets.JWT_SECRET}}"
            "DATABASE_USER=${{ secrets.DATABASE_USER }}"
            "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}"
            "BUCKET_NAME=sq-chatapp-prod"
            "PORT=80"

